@startuml

!theme C4_brown from https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/themes
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include <C4/C4_Context>
!include ./include.puml

skinparam dpi 200

rectangle "r2" as r2 {
  rectangle r
}

node "with text" as n

interface "i" as int

System(system, "system", "desc")

System_Boundary(sys, "boundary") {
    ' This is a comment
    Container(con, "container", "tech", "description")
}

Rel(system, con, "text")

' This is a comment
together {
  circle "circle text" as c
  /'
        ' this is not allowed
  '/
  hexagon h
}

/'
 text
'/
database "database" as db #line.dashed:red /' this is allowed '/

/'
' another comment '/
hexagon "database" as hex #line.dashed:red {
    circle circ
}

Container(tag, "text", "tech", "desc", $sprite="python")


h -> c

c --> h

h -[hidden]-> n

n -[hidden] r

r <-[hidden]- n

r <-l-> n

@enduml
