@startuml

!theme C4_brown from https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/themes
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include <C4/C4_Context>
!include ./include.puml

skinparam dpi 200

rectangle r

node "with text" as n

interface "i" as int

System(system, "system", "desc")

System_Boundary(sys, "boundary") {
    Container(con, "container", "tech", "description")
}

Rel(system, con, "text")

together {
  circle "circle text" as c
  hexagon h
}

database "database" as db #line.dashed:red

hexagon "database" as hex #line.dashed:red {
    circle circ
}

' This is a comment

/'
' this is a block comment
'/

h -> c

c --> h

h -[hidden]-> n

n -[hidden] r

r <-[hidden]- n

r <-l-> n

@enduml
